name: Bug Report
description: >-
  Report a bug or regression in the Archipelago core (Generator, MultiServer, CommonClient, etc.) or WebHost.
title: '[Bug]: '
labels:
  - 'is: bug/fix'
body:
  - type: markdown
    attributes:
      value: >-
        Thanks for taking the time to fill out a bug report! If this problem occurred during local generation, check
        your Archipelago install for a log and upload it with this report, as well as any YAML files used.
        
        
        ### Disclaimer for Individual World Reports


        This form should only be used in relation to core Archipelago components. All bug reports or requests in/for 
        individual worlds (games) should instead be relayed to the maintainer(s) of the world itself.


        For games currently in this repository, check the website's supported games page for a link to submit bug 
        reports for the game, if present, or submit a bug report in our [Discord](https://discord.gg/archipelago)
        server's [#bug-reports](https://discord.com/channels/731205301247803413/1009605416428257360) forum and ping the 
        relevant maintainers.
        
        
        A list of maintainers for each world (game) in this repository is also documented in our 
        [CODEOWNERS](https://github.com/ArchipelagoMW/Archipelago/blob/main/docs/CODEOWNERS) documentation.
  - type: input
    id: version
    attributes:
      label: Archipelago Version
      description: >-
        What version of Archipelago was this problem detected in?


        - If running from a RC, include the RC number, in addition to the version number.

        - If running from source, include the commit hash (`git rev-parse HEAD` returns the current HEAD's hash; 
        e.g., `f06e565`).
      placeholder: e.g., 0.4.6 / 0.5.0 RC2 / f06e565
    validations:
      required: true
  - type: dropdown
    id: affects
    attributes:
      label: Affected Components
      description: Select all the Archipelago components that are affected by this problem.
      multiple: true
      options:
        - Generation
        - MultiServer
        - Launcher
        - Client
        - WebHost
        - Installer
        - Documentation
        - AutoWorld API
        - Other Component(s)
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the problem and what outcome was expected, if applicable.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Minimal Reproduction
      description: Provide steps to reproduce the problem.
  - type: textarea
    id: files
    attributes:
      label: Logs & Additional Files
      description: >-
        Include any applicable logs, YAML files, spoiler outputs, or other files that were outputted or used in relation
        to this problem, if applicable.
        
        
        - If the problem occurred locally, you can find these logs in your Archipelago directory by clicking 
        `Browse Files` in the Archipelago Launcher and navigating to the `logs` directory.
